/**
 * Lista de dominios de correos temporales/desechables que deben ser bloqueados
 * Actualizada con los servicios más populares de correo temporal
 */

export const DISPOSABLE_EMAIL_DOMAINS = [
  // Servicios populares de correo temporal
  '10minutemail.com',
  '10minutemail.net',
  'tempmail.com',
  'temp-mail.org',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'sharklasers.com',
  'spam4.me',
  'grr.la',
  'maildrop.cc',
  'mailinator.com',
  'trashmail.com',
  'yopmail.com',
  'fakeinbox.com',
  'throwaway.email',
  'getnada.com',
  'mohmal.com',
  'dispostable.com',
  'mailnesia.com',
  'mintemail.com',
  'mytemp.email',
  'spamgourmet.com',
  'tempail.com',
  'tempmailaddress.com',
  'emailondeck.com',
  'jetable.org',
  'no-spam.ws',
  'spam.la',
  'spambox.us',
  'tempemail.com',
  'tempr.email',
  'throwawaymail.com',
  'trashinbox.net',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'zemail.info',
  'zzz.com',
  '33mail.com',
  'anonbox.net',
  'binkmail.com',
  'bodhi.lawlita.com',
  'cool.fr.nf',
  'courriel.fr.nf',
  'courrieltemporaire.com',
  'crapmail.org',
  'deadaddress.com',
  'despam.it',
  'disposemail.com',
  'dontreg.com',
  'e4ward.com',
  'emailsensei.com',
  'emailtemporanea.com',
  'emailtemporanea.net',
  'emailtemporar.ro',
  'emailtemporario.com.br',
  'emltmp.com',
  'fakemailgenerator.com',
  'fastmail.fm',
  'filzmail.com',
  'fr33mail.info',
  'getairmail.com',
  'hidemail.de',
  'inbox.si',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'keepmymail.com',
  'klzlk.com',
  'kurzepost.de',
  'lags.us',
  'links2.net',
  'litedrop.com',
  'lol.ovpn.to',
  'mailbidon.com',
  'mailcatch.com',
  'mailexpire.com',
  'mailforspam.com',
  'mailin8r.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnull.com',
  'mailsac.com',
  'mailtemp.info',
  'mailtome.de',
  'mailtothis.com',
  'mailzi.ru',
  'mt2009.com',
  'mt2014.com',
  'mytrashmail.com',
  'nobulk.com',
  'noclickemail.com',
  'nospam.ze.tc',
  'nospamfor.us',
  'objectmail.com',
  'obobbo.com',
  'oneoffemail.com',
  'pookmail.com',
  'proxymail.eu',
  'rcpt.at',
  'safersignup.de',
  'sharklasers.com',
  'shiftmail.com',
  'slaskpost.se',
  'spamavert.com',
  'spambob.com',
  'spambog.com',
  'spambox.info',
  'spambox.irishspringrealty.com',
  'spamcero.com',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamhole.com',
  'spamify.com',
  'spammotel.com',
  'spamobox.com',
  'spamslicer.com',
  'spamspot.com',
  'spamthis.co.uk',
  'spamtrail.com',
  'speed.1s.fr',
  'supergreatmail.com',
  'supermailer.jp',
  'teewars.org',
  'temp-mail.de',
  'temp-mail.ru',
  'tempemail.co.za',
  'tempemail.net',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.it',
  'tempmail2.com',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'thankyou2010.com',
  'thisisnotmyrealemail.com',
  'throwawayemailaddress.com',
  'tilien.com',
  'tmailinator.com',
  'trashdevil.com',
  'trashmail.de',
  'trashmail.net',
  'trashmail.org',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'tyldd.com',
  'uggsrock.com',
  'veryrealemail.com',
  'viditag.com',
  'viralplays.com',
  'vpn.st',
  'wasteland.rfc822.org',
  'webemail.me',
  'webm4il.info',
  'wh4f.org',
  'whyspam.me',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'www.e4ward.com',
  'www.gishpuppy.com',
  'www.mailinator.com',
  'wwwnew.eu',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.fr',
  'yopmail.net',
  'ypmail.webarnak.fr.eu.org',
  'yuurok.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zippymail.info',
  'zoemail.com',
  'zomg.info'
];

/**
 * Verifica si un dominio de email es temporal/desechable
 * @param {string} email - Email a verificar
 * @returns {boolean} - true si es temporal, false si no
 */
export const isDisposableEmail = (email) => {
  if (!email || typeof email !== 'string') return false;
  
  const domain = email.toLowerCase().split('@')[1];
  if (!domain) return false;
  
  return DISPOSABLE_EMAIL_DOMAINS.includes(domain);
};

/**
 * Obtiene el nombre del dominio de un email
 * @param {string} email - Email del cual extraer el dominio
 * @returns {string} - Dominio del email
 */
export const getEmailDomain = (email) => {
  if (!email || typeof email !== 'string') return '';
  return email.toLowerCase().split('@')[1] || '';
};

export default {
  DISPOSABLE_EMAIL_DOMAINS,
  isDisposableEmail,
  getEmailDomain
};

export const ALLOWED_EMAIL_DOMAINS = [
  'gmail.com',
  'hotmail.com',
  'upao.edu.pe'
];

